/**
 * f2fs_metadata.cpp — F2FS metadata serialisation
 *
 * Three output files:
 *   fs_config.txt      — path uid gid mode caps (AOSP fs_config format)
 *   file_contexts.txt  — path label (SELinux, only entries with a label)
 *   f2fs_special.txt   — F2FS-specific per-file attributes
 *
 * f2fs_special.txt format (one line per entry that has at least one attribute):
 *
 *   <path>  <attr> [<attr> ...]
 *
 * Attributes:
 *   compress:algo=<lzo|lz4|zstd|lzorle>,log_cluster=<n>,saved_blocks=<n>[,released]
 *   encrypt
 *   inline_data
 *   inline_dents
 *   pinned
 */

#include "f2fs_metadata.h"
#include "../include/f2fs_fs.h"

#include <algorithm>
#include <cerrno>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <sys/stat.h>
#include "win_pread.h"

namespace fs = std::filesystem;

// ════════════════════════════════════════════════════════════════════════════
// xattr name-index → string prefix
// ════════════════════════════════════════════════════════════════════════════

static const char* xattr_prefix(uint8_t index)
{
    switch (index) {
    case XATTR_INDEX_USER:                    return "user.";
    case XATTR_INDEX_POSIX_ACL_ACCESS:        return "system.posix_acl_access";
    case XATTR_INDEX_POSIX_ACL_DEFAULT:       return "system.posix_acl_default";
    case XATTR_INDEX_TRUSTED:                 return "trusted.";
    case XATTR_INDEX_SECURITY:                return "security.";
    case XATTR_INDEX_SYSTEM:                  return "system.";
    default:                                  return "";
    }
}

// ════════════════════════════════════════════════════════════════════════════
// parseXAttrBlock
// ════════════════════════════════════════════════════════════════════════════

XAttrMap parseXAttrBlock(const uint8_t* data, size_t size)
{
    XAttrMap out;
    if (!data || size < sizeof(f2fs_xattr_header)) return out;

    const auto* hdr = reinterpret_cast<const f2fs_xattr_header*>(data);
    if (hdr->h_magic != F2FS_XATTR_MAGIC) return out;

    const uint8_t* ptr = data + sizeof(f2fs_xattr_header);
    const uint8_t* end = data + size;

    while (ptr + sizeof(f2fs_xattr_entry) <= end) {
        const auto* e = reinterpret_cast<const f2fs_xattr_entry*>(ptr);
        if (e->e_name_len == 0 && e->e_value_size == 0) break;

        const uint8_t* name_ptr  = ptr + sizeof(f2fs_xattr_entry);
        const uint8_t* value_ptr = name_ptr + e->e_name_len;
        const uint8_t* next_ptr  = reinterpret_cast<const uint8_t*>(xattr_next_entry(e));

        if (value_ptr > end || value_ptr + e->e_value_size > end) break;
        if (next_ptr  > end + 4) break;

        std::string name = xattr_prefix(e->e_name_index);
        if (e->e_name_index != XATTR_INDEX_POSIX_ACL_ACCESS &&
            e->e_name_index != XATTR_INDEX_POSIX_ACL_DEFAULT) {
            name.append(reinterpret_cast<const char*>(name_ptr), e->e_name_len);
        }
        out.emplace(name, std::vector<uint8_t>(value_ptr, value_ptr + e->e_value_size));
        ptr = next_ptr;
    }
    return out;
}

// ════════════════════════════════════════════════════════════════════════════
// Helpers
// ════════════════════════════════════════════════════════════════════════════

std::string MetadataWriter::octalMode(uint16_t mode)
{
    char buf[8];
    snprintf(buf, sizeof(buf), "%04o", mode & 07777u);
    return buf;
}

std::string MetadataWriter::typeChar(uint16_t mode)
{
    if      (S_ISREG(mode))  return "file";
    else if (S_ISDIR(mode))  return "dir";
    else if (S_ISLNK(mode))  return "symlink";
    else if (S_ISBLK(mode))  return "block";
    else if (S_ISCHR(mode))  return "char";
    else if (S_ISFIFO(mode)) return "fifo";
    else if (S_ISSOCK(mode)) return "socket";
    return "unknown";
}

// ════════════════════════════════════════════════════════════════════════════
// writeFsConfig  — path uid gid mode caps (sorted by path)
// ════════════════════════════════════════════════════════════════════════════

bool MetadataWriter::writeFsConfig(const std::string& path) const
{
    FILE* f = fopen(path.c_str(), "wb");
    if (!f) {
        fprintf(stderr, "[ERR] Cannot open %s: %s\n", path.c_str(), strerror(errno));
        return false;
    }

    fputs("# fs_config — generated by f2fs_extract\n"
          "# format: path uid gid mode capabilities\n", f);

    std::vector<const FileMetadata*> sorted;
    sorted.reserve(entries_.size());
    for (const auto& m : entries_) sorted.push_back(&m);
    std::sort(sorted.begin(), sorted.end(),
              [](const FileMetadata* a, const FileMetadata* b){
                  return a->path < b->path;
              });

    for (const auto* m : sorted) {
        char caps_str[32];
        if (m->has_caps && m->capabilities)
            snprintf(caps_str, sizeof(caps_str), "0x%016llx",
                     (unsigned long long)m->capabilities);
        else
            strcpy(caps_str, "0");

        std::string p = m->path.empty() ? "/" : m->path;
        fprintf(f, "%s %u %u %s %s\n",
                p.c_str(), m->uid, m->gid,
                octalMode(m->mode).c_str(), caps_str);
    }

    fclose(f);
    return true;
}

// ════════════════════════════════════════════════════════════════════════════
// writeFileContexts  — path  label  (only entries with a SELinux label)
// ════════════════════════════════════════════════════════════════════════════

bool MetadataWriter::writeFileContexts(const std::string& path) const
{
    FILE* f = fopen(path.c_str(), "wb");
    if (!f) {
        fprintf(stderr, "[ERR] Cannot open %s: %s\n", path.c_str(), strerror(errno));
        return false;
    }

    fputs("# file_contexts — generated by f2fs_extract\n"
          "# format: path  selinux_label\n", f);

    std::vector<const FileMetadata*> sorted;
    for (const auto& m : entries_)
        if (!m.selinux_label.empty()) sorted.push_back(&m);
    std::sort(sorted.begin(), sorted.end(),
              [](const FileMetadata* a, const FileMetadata* b){
                  return a->path < b->path;
              });

    for (const auto* m : sorted)
        fprintf(f, "%s\t%s\n", m->path.c_str(), m->selinux_label.c_str());

    fclose(f);
    return true;
}

// ════════════════════════════════════════════════════════════════════════════
// writeF2FSSpecial  — F2FS-specific per-file attributes
// ════════════════════════════════════════════════════════════════════════════

bool MetadataWriter::writeF2FSSpecial(const std::string& path) const
{
    static const char* algo_name[] = {"lzo", "lz4", "zstd", "lzorle"};

    FILE* f = fopen(path.c_str(), "wb");
    if (!f) {
        fprintf(stderr, "[ERR] Cannot open %s: %s\n", path.c_str(), strerror(errno));
        return false;
    }

    fputs("# f2fs_special — F2FS-specific per-file attributes\n"
          "# Generated by f2fs_extract\n"
          "# format: path  attribute  [attribute ...]\n"
          "#\n"
          "# Attributes:\n"
          "#   compress:algo=<lzo|lz4|zstd|lzorle>,log_cluster=<n>,saved_blocks=<n>[,released]\n"
          "#     log_cluster: cluster = (1 << n) pages = (1 << n) x 4096 bytes\n"
          "#     saved_blocks: number of 4K blocks saved by compression\n"
          "#     released: compressed blocks were freed (COMPRESS_RELEASED flag)\n"
          "#   encrypt     — file content is encrypted (FBE)\n"
          "#   inline_data — file content stored inside the inode block\n"
          "#   inline_dents — directory entries stored inside the inode block\n"
          "#   pinned      — file pinned in place, GC will not move it\n"
          "#\n"
          "# Only entries with at least one F2FS-specific attribute are listed.\n"
          "# Files without any such attribute are omitted (standard POSIX behaviour).\n",
          f);

    std::vector<const FileMetadata*> sorted;
    for (const auto& m : entries_) {
        if (m.f2fs_compressed || m.f2fs_encrypted ||
            m.f2fs_inline_data || m.f2fs_inline_dents || m.f2fs_pinned)
            sorted.push_back(&m);
    }
    std::sort(sorted.begin(), sorted.end(),
              [](const FileMetadata* a, const FileMetadata* b){
                  return a->path < b->path;
              });

    for (const auto* m : sorted) {
        std::string p = m->path.empty() ? "/" : m->path;
        fprintf(f, "%s", p.c_str());

        if (m->f2fs_compressed) {
            const char* aname = (m->compress_algo < 4)
                                ? algo_name[m->compress_algo] : "unknown";
            fprintf(f, "\tcompress:algo=%s,log_cluster=%u,saved_blocks=%llu%s",
                    aname,
                    (unsigned)m->log_cluster_size,
                    (unsigned long long)m->compr_blocks,
                    m->compress_released ? ",released" : "");
        }
        if (m->f2fs_encrypted)    fputs("\tencrypt",      f);
        if (m->f2fs_inline_data)  fputs("\tinline_data",  f);
        if (m->f2fs_inline_dents) fputs("\tinline_dents", f);
        if (m->f2fs_pinned)       fputs("\tpinned",       f);

        fputc('\n', f);
    }

    fclose(f);
    return true;
}

// ════════════════════════════════════════════════════════════════════════════
// writeAll
// ════════════════════════════════════════════════════════════════════════════

bool MetadataWriter::writeAll(const std::string& dir) const
{
    std::error_code ec;
    fs::create_directories(dir, ec);
    if (ec) {
        fprintf(stderr, "[ERR] Cannot create metadata dir %s: %s\n",
                dir.c_str(), ec.message().c_str());
        return false;
    }

    bool ok = true;
    ok &= writeFsConfig    (dir + "/fs_config.txt");
    ok &= writeFileContexts(dir + "/file_contexts.txt");
    ok &= writeF2FSSpecial (dir + "/f2fs_special.txt");

    if (ok)
        fprintf(stdout, "Metadata written to %s/\n", dir.c_str());
    return ok;
}
